// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (project_id, status)
VALUES ($1, $2)
RETURNING id, project_id, status, url, created_at, updated_at
`

type CreateDeploymentParams struct {
	ProjectID uuid.UUID
	Status    string
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment, arg.ProjectID, arg.Status)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, project_id, status, url, created_at, updated_at FROM deployments
WHERE id = $1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentByIDAndUser = `-- name: GetDeploymentByIDAndUser :one
SELECT d.id, d.project_id, d.status, d.url, d.created_at, d.updated_at
FROM deployments d
JOIN projects p
ON d.project_id = p.id
WHERE d.id = $1
AND p.user_id = $2
`

type GetDeploymentByIDAndUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDeploymentByIDAndUser(ctx context.Context, arg GetDeploymentByIDAndUserParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByIDAndUser, arg.ID, arg.UserID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentByPrefix = `-- name: GetDeploymentByPrefix :one
SELECT id, project_id, status, url, created_at, updated_at
FROM deployments
WHERE id::text LIKE $1 || '%'
LIMIT 1
`

func (q *Queries) GetDeploymentByPrefix(ctx context.Context, dollar_1 sql.NullString) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByPrefix, dollar_1)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentsByProject = `-- name: GetDeploymentsByProject :many
SELECT id, project_id, status, url, created_at, updated_at
FROM deployments
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetDeploymentsByProject(ctx context.Context, projectID uuid.UUID) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextDeployment = `-- name: GetNextDeployment :one
WITH next_job AS (
    SELECT id
    FROM deployments
    WHERE status = 'queued'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE deployments
SET status = 'building',
    updated_at = NOW()
WHERE id = (
    SELECT id FROM next_job
)
RETURNING id, project_id, status, url, created_at, updated_at
`

func (q *Queries) GetNextDeployment(ctx context.Context) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getNextDeployment)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeploymentFailed = `-- name: MarkDeploymentFailed :exec
UPDATE deployments
SET status = 'failed',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkDeploymentFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markDeploymentFailed, id)
	return err
}

const markDeploymentSuccess = `-- name: MarkDeploymentSuccess :exec
UPDATE deployments
SET STATUS = 'success',
    url = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkDeploymentSuccessParams struct {
	ID  uuid.UUID
	Url sql.NullString
}

func (q *Queries) MarkDeploymentSuccess(ctx context.Context, arg MarkDeploymentSuccessParams) error {
	_, err := q.db.ExecContext(ctx, markDeploymentSuccess, arg.ID, arg.Url)
	return err
}

const resetBuildingDeployments = `-- name: ResetBuildingDeployments :exec
UPDATE deployments
SET status = 'queued',
    updated_at = NOW()
WHERE status = 'building'
AND updated_at < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) ResetBuildingDeployments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetBuildingDeployments)
	return err
}
