// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (project_id, status, repo_url)
VALUES ($1, $2, $3)
RETURNING id, project_id, status, repo_url, url, created_at, updated_at
`

type CreateDeploymentParams struct {
	ProjectID uuid.UUID
	Status    string
	RepoUrl   string
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment, arg.ProjectID, arg.Status, arg.RepoUrl)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.RepoUrl,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, project_id, status, repo_url, url, created_at, updated_at FROM deployments
WHERE id = $1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.RepoUrl,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextDeployment = `-- name: GetNextDeployment :one
UPDATE deployments
SET status = 'building',
    updated_at = NOW()
WHERE id = (
    SELECT id
    FROM deployments
    WHERE status = 'queued'
    ORDER BY created_at
    LIMIT 1
)
RETURNING id, project_id, status, repo_url, url, created_at, updated_at
`

func (q *Queries) GetNextDeployment(ctx context.Context) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getNextDeployment)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.RepoUrl,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeploymentFailed = `-- name: MarkDeploymentFailed :exec
UPDATE deployments
SET status = 'failed',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkDeploymentFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markDeploymentFailed, id)
	return err
}

const markDeploymentSuccess = `-- name: MarkDeploymentSuccess :exec
UPDATE deployments
SET STATUS = 'success',
    url = $2,
    updated_at = NOW()
WHERE id = $1
`

type MarkDeploymentSuccessParams struct {
	ID  uuid.UUID
	Url sql.NullString
}

func (q *Queries) MarkDeploymentSuccess(ctx context.Context, arg MarkDeploymentSuccessParams) error {
	_, err := q.db.ExecContext(ctx, markDeploymentSuccess, arg.ID, arg.Url)
	return err
}
