// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployment_logs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createDeploymentLog = `-- name: CreateDeploymentLog :exec
INSERT INTO deployment_logs (
    deployment_id,
    log
)
VALUES ($1, $2)
`

type CreateDeploymentLogParams struct {
	DeploymentID uuid.UUID
	Log          string
}

func (q *Queries) CreateDeploymentLog(ctx context.Context, arg CreateDeploymentLogParams) error {
	_, err := q.db.ExecContext(ctx, createDeploymentLog, arg.DeploymentID, arg.Log)
	return err
}

const getDeploymentLogs = `-- name: GetDeploymentLogs :many
SELECT id, deployment_id, log, created_at
FROM deployment_logs
WHERE deployment_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetDeploymentLogs(ctx context.Context, deploymentID uuid.UUID) ([]DeploymentLog, error) {
	rows, err := q.db.QueryContext(ctx, getDeploymentLogs, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentLog
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Log,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
