// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Deployment struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Status    string
	RepoUrl   string
	Url       sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Project struct {
	ID        uuid.UUID
	Name      string
	UserID    uuid.UUID
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Email     string
}
