// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Deployment struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Status    string
	Url       sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DeploymentLog struct {
	ID           uuid.UUID
	DeploymentID uuid.UUID
	Log          string
	CreatedAt    time.Time
}

type Project struct {
	ID             uuid.UUID
	Name           string
	UserID         uuid.UUID
	CreatedAt      time.Time
	InstallCommand string
	BuildCommand   string
	OutputDir      string
	RepoUrl        string
	UpdatedAt      time.Time
	GithubRepoID   sql.NullInt64
	Branch         string
	AutoDeploy     bool
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	Email         string
	PasswordHash  sql.NullString
	Provider      string
	ProviderID    sql.NullString
	AvatarUrl     sql.NullString
	EmailVerified bool
}
