// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_accounts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts(
    user_id,
    provider,
    provider_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, provider, provider_id, created_at, updated_at
`

type CreateOAuthAccountParams struct {
	UserID     uuid.UUID
	Provider   string
	ProviderID string
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, createOAuthAccount, arg.UserID, arg.Provider, arg.ProviderID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_id, created_at, updated_at
FROM oauth_accounts
WHERE provider = $1
AND provider_id = $2
`

type GetOAuthAccountParams struct {
	Provider   string
	ProviderID string
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccount, arg.Provider, arg.ProviderID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOAuth = `-- name: GetUserByOAuth :one
SELECT users.id, users.created_at, users.updated_at, users.name, users.email, users.password_hash, users.avatar_url, users.email_verified
FROM users
JOIN oauth_accounts
ON users.id = oauth_accounts.user_id
WHERE oauth_accounts.provider = $1
AND oauth_accounts.provider_id = $2
`

type GetUserByOAuthParams struct {
	Provider   string
	ProviderID string
}

func (q *Queries) GetUserByOAuth(ctx context.Context, arg GetUserByOAuthParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByOAuth, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.EmailVerified,
	)
	return i, err
}
