// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    name, 
    user_id, 
    repo_url, 
    install_command, 
    build_command, 
    output_dir,
    github_repo_id,
    branch,
    auto_deploy
)
VALUES(
    $1,$2,$3,$4,$5,$6,$7,$8,$9
)
RETURNING id, name, user_id, created_at, install_command, build_command, output_dir, repo_url, updated_at, github_repo_id, branch, auto_deploy
`

type CreateProjectParams struct {
	Name           string
	UserID         uuid.UUID
	RepoUrl        string
	InstallCommand string
	BuildCommand   string
	OutputDir      string
	GithubRepoID   sql.NullInt64
	Branch         string
	AutoDeploy     bool
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Name,
		arg.UserID,
		arg.RepoUrl,
		arg.InstallCommand,
		arg.BuildCommand,
		arg.OutputDir,
		arg.GithubRepoID,
		arg.Branch,
		arg.AutoDeploy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.InstallCommand,
		&i.BuildCommand,
		&i.OutputDir,
		&i.RepoUrl,
		&i.UpdatedAt,
		&i.GithubRepoID,
		&i.Branch,
		&i.AutoDeploy,
	)
	return i, err
}

const getProjectByGithubRepoID = `-- name: GetProjectByGithubRepoID :one
SELECT id, name, user_id, created_at, install_command, build_command, output_dir, repo_url, updated_at, github_repo_id, branch, auto_deploy
FROM projects
WHERE github_repo_id = $1
AND auto_deploy = true
`

func (q *Queries) GetProjectByGithubRepoID(ctx context.Context, githubRepoID sql.NullInt64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByGithubRepoID, githubRepoID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.InstallCommand,
		&i.BuildCommand,
		&i.OutputDir,
		&i.RepoUrl,
		&i.UpdatedAt,
		&i.GithubRepoID,
		&i.Branch,
		&i.AutoDeploy,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, user_id, created_at, install_command, build_command, output_dir, repo_url, updated_at, github_repo_id, branch, auto_deploy FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.InstallCommand,
		&i.BuildCommand,
		&i.OutputDir,
		&i.RepoUrl,
		&i.UpdatedAt,
		&i.GithubRepoID,
		&i.Branch,
		&i.AutoDeploy,
	)
	return i, err
}

const getProjectsByUsers = `-- name: GetProjectsByUsers :many
SELECT id, name, user_id, created_at, install_command, build_command, output_dir, repo_url, updated_at, github_repo_id, branch, auto_deploy FROM projects
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetProjectsByUsers(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsByUsers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
			&i.InstallCommand,
			&i.BuildCommand,
			&i.OutputDir,
			&i.RepoUrl,
			&i.UpdatedAt,
			&i.GithubRepoID,
			&i.Branch,
			&i.AutoDeploy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
