// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name,
    email,
    password_hash,
    provider,
    provider_id,
    avatar_url,
    email_verified
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, created_at, updated_at, name, email, password_hash, provider, provider_id, avatar_url, email_verified
`

type CreateUserParams struct {
	Name          string
	Email         string
	PasswordHash  sql.NullString
	Provider      string
	ProviderID    sql.NullString
	AvatarUrl     sql.NullString
	EmailVerified bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Provider,
		arg.ProviderID,
		arg.AvatarUrl,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Provider,
		&i.ProviderID,
		&i.AvatarUrl,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, name, email, password_hash, provider, provider_id, avatar_url, email_verified FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Provider,
		&i.ProviderID,
		&i.AvatarUrl,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, name, email, password_hash, provider, provider_id, avatar_url, email_verified
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Provider,
		&i.ProviderID,
		&i.AvatarUrl,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT id, created_at, updated_at, name, email, password_hash, provider, provider_id, avatar_url, email_verified
FROM users
WHERE provider = $1
AND provider_id = $2
`

type GetUserByProviderParams struct {
	Provider   string
	ProviderID sql.NullString
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProvider, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Provider,
		&i.ProviderID,
		&i.AvatarUrl,
		&i.EmailVerified,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = $2,
    avatar_url = $3,
    email_verified = $4
WHERE id = $1
RETURNING id, created_at, updated_at, name, email, password_hash, provider, provider_id, avatar_url, email_verified
`

type UpdateUserParams struct {
	ID            uuid.UUID
	Name          string
	AvatarUrl     sql.NullString
	EmailVerified bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.AvatarUrl,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Provider,
		&i.ProviderID,
		&i.AvatarUrl,
		&i.EmailVerified,
	)
	return i, err
}
